[package]
name = "rypy"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.22"
simplelog = "0.12"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.128"
tree-sitter = "0.24.6"
salsa = "0.16.1"
tree-sitter-python = "0.23.6"

[[bin]]
name = "rypy"
path = "./src/main.rs"
